server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://192.168.211.160:8761/eureka/,http://192.168.211.160:8762/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: microservice-movie,microservice-movie2
  cluster-name-expression: "'default'"
